compressionLevel: mixed

logFilters:
  - code: YN0060
    level: error
  - code: YN0002
    level: error
  - level: discard
    pattern: "react is listed by your project with version *, which doesn't satisfy"
  - level: discard
    pattern: "react-dom is listed by your project with version *, which doesn't satisfy"
  - level: discard
    pattern: "react-router-dom is listed by your project with version *, which doesn't satisfy what @jsq/ds"

nodeLinker: pnp

npmRegistryServer: "https://jsq-972451838497.d.codeartifact.us-west-2.amazonaws.com/npm/shared/"

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: 601D8C0E-5DEC-44BE-8003-60BF442C5E09
    npmRegistryServer: "https://npm.fontawesome.com/"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
  os:
    - linux
    - darwin
