name: Check PR title

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - "main"

jobs:
  check-pr-title:
    uses: junipersquare/github-actions-workflows/.github/workflows/check-pr-title.yaml@main
    with:
      check-jira-issue: true
      check-conventional-commit: true
    secrets: inherit