name: Preview deploy

on:
  pull_request:
    types:
      - synchronize
      - labeled
      - reopened

env:
  HELM_CHART_VERSION: v1.0.372

  AWS_ROLE_ARN: arn:aws:iam::972451838497:role/terraform-dev
  AWS_ACCOUNT_ID: 972451838497
  AWS_ROLE_DURATION_SECONDS: 1200
  AWS_DEFAULT_REGION: us-west-2
  YAML_REPO: https://github.com/junipersquare/application-manifests.git
  NODE_ENV: production
  CACHE_REPO: docker-registry.docker-registry:5000
  CACHE_INSECURE: true

jobs:
  docker-build:
    name: Docker Build
    if: ${{ ((github.event.action == 'synchronize' || github.event.action == 'reopened') && contains(github.event.pull_request.labels.*.name, 'preview')) || (github.event.action == 'labeled' && github.event.label.name == 'preview') }}
    strategy:
      fail-fast: true
      matrix:
        arch: [amd]
    runs-on: ["junipersquare-2vcpu-4gb-${{ matrix.arch }}"]
    steps:
      - name: Git Checkout
        id: git-checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          submodules: recursive
          token: ${{ secrets.GITOPS_TOKEN }}

      - name: Login to Dockerhub
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Configure AWS Credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2
        with:
          aws-access-key-id: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-duration-seconds: ${{ env.AWS_ROLE_DURATION_SECONDS }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Login to AWS Elastic Container Registry
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@b874a33292cc9887d2e80bc63f6f1a11fccb4a7b

      - name: Create Registry
        uses: int128/create-ecr-repository-action@27f3792ed9a92a1dacc078ca944b844dedfe270d
        id: create-registry
        with:
          repository: ${{ github.event.repository.name }}
          public: false

      - name: Set up Docker Context
        id: setup-docker-context
        run: docker context create builders

      - name: Set up Docker Buildx
        id: setup-docker-buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6
        with:
          endpoint: builders
          config-inline: |
            [registry."${{ env.CACHE_REPO }}"]
              http = true
              insecure = ${{ env.CACHE_INSECURE }}

      - name: Set environment variables
        id: meta
        run: |
          echo "deployment_hash=$(git rev-parse --short ${{github.event.pull_request.head.sha}})" >> $GITHUB_OUTPUT

      - name: Get Node Version
        id: get-node-version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Create empty .env file
        id: empty-dot-env
        run: touch .env

      - name: Build and Push to AWS Elastic Container Registry
        id: build-and-push
        uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com/${{ github.event.repository.name }}:${{ steps.meta.outputs.deployment_hash }}-${{ matrix.arch }}
          platforms: linux/${{ matrix.arch }}64
          build-args: |
            NODE_VERSION=${{ env.NODE_VERSION }}
          cache-from: type=registry,ref=${{ env.CACHE_REPO }}/${{ github.event.repository.name }}:buildcache-${{ matrix.arch }}
          cache-to: type=registry,ref=${{ env.CACHE_REPO }}/${{ github.event.repository.name }}:buildcache-${{ matrix.arch }},mode=max

  # combine-images:
  #   name: Combine Docker Images
  #   if: ${{ ((github.event.action == 'synchronize' || github.event.action == 'reopened') && contains(github.event.pull_request.labels.*.name, 'preview')) || (github.event.action == 'labeled' && github.event.label.name == 'preview') }}
  #   runs-on: [junipersquare-1vcpu-2gb-amd]
  #   needs: [docker-build]
  #   steps:
  #     - name: Git Checkout
  #       id: git-checkout
  #       uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
  #       with:
  #         submodules: recursive
  #         token: ${{ secrets.GITOPS_TOKEN }}

  #     - name: Configure AWS Credentials
  #       id: configure-aws-credentials
  #       uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2
  #       with:
  #         aws-access-key-id: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
  #         role-to-assume: ${{ env.AWS_ROLE_ARN }}
  #         role-duration-seconds: ${{ env.AWS_ROLE_DURATION_SECONDS }}
  #         aws-region: ${{ env.AWS_DEFAULT_REGION }}

  #     - name: Login to AWS Elastic Container Registry
  #       id: login-ecr
  #       uses: aws-actions/amazon-ecr-login@b874a33292cc9887d2e80bc63f6f1a11fccb4a7b

  #     - name: Set environment variables
  #       id: meta
  #       run: |
  #         echo "deployment_hash=$(git rev-parse --short ${{github.event.pull_request.head.sha}})" >> $GITHUB_OUTPUT
  #     - name: Combine container images
  #       id: combine-docker-images
  #       run: |
  #         docker manifest create \
  #         ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com/${{ github.event.repository.name }}:${{ steps.meta.outputs.deployment_hash }} \
  #         --amend ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com/${{ github.event.repository.name }}:${{ steps.meta.outputs.deployment_hash }}-amd \
  #         --amend ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com/${{ github.event.repository.name }}:${{ steps.meta.outputs.deployment_hash }}-arm
  #         docker manifest push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com/${{ github.event.repository.name }}:${{ steps.meta.outputs.deployment_hash }}

  deploy-preview:
    name: Deploy K8s Manifests
    runs-on: [junipersquare-1vcpu-2gb-amd]
    needs: [docker-build]
    if: ${{ ((github.event.action == 'synchronize' || github.event.action == 'reopened') && contains(github.event.pull_request.labels.*.name, 'preview')) || (github.event.action == 'labeled' && github.event.label.name == 'preview') }}
    steps:
      - name: Git Checkout
        id: git-checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Variables
        id: vars
        run: |
          echo "deployment_hash=$(git rev-parse --short ${{github.event.pull_request.head.sha}})" >> $GITHUB_OUTPUT
          echo "pr_number=${{github.event.number}}" >> $GITHUB_OUTPUT

      - name: Create GitHub deployment
        id: create-github-deployment
        uses: chrnorm/deployment-action@1b599fe41a0ef1f95191e7f2eec4743f2d7dfc48
        with:
          token: "${{ github.token }}"
          environment-url: https://fund-admin.pr${{ github.event.number }}.preview.junipersquare.us
          environment: pr${{ github.event.number }}

      - uses: azure/setup-helm@b5b231a831f96336bbfeccc1329990f0005c5bb1
        with:
          version: "v3.9.0" # default is latest (stable)
        id: install-helm

      - name: Helm Chart Login
        id: helm-chart-login
        run: |
          echo $GCR | helm registry login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
        env:
          HELM_EXPERIMENTAL_OCI: 1

      - name: Create K8s Manifest
        id: create-k8s-manifest
        run: |
          mkdir -p ${{ github.event.number }}/manifests && \
          helm template \
            --debug \
            --set global.image.repository=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com/${{ github.event.repository.name }} \
            --set global.image.tag=${{ steps.vars.outputs.deployment_hash }}-amd \
            --set global.github.deploymentId=${{ steps.create-github-deployment.outputs.deployment_id }} \
            --set global.github.prNumber=${{ github.event.number }} \
            --namespace ${{ github.event.number }} --set global.namespace=${{ github.event.number }} --create-namespace  \
            ${{ github.event.number }}-${{ github.event.repository.name }} oci://ghcr.io/junipersquare/universal-chart --version ${{ env.HELM_CHART_VERSION }} -f ./infra/values-preview.yaml > ${{ github.event.number }}/manifests/manifest.yaml

      - name: Create config.json
        id: create-config-json
        run: |
          jq --null-input \
            --arg appName "${{ github.event.repository.name }}-pr${{ github.event.number }}" \
            --arg userGivenName frontend-pr${{ github.event.number }} \
            --arg destNamespace "${{ github.event.repository.name }}-preview" \
            --arg destServer "https://kubernetes.default.svc" \
            --arg srcPath "${{ github.event.repository.name }}/preview/${{ github.event.number }}/manifests" \
            --arg srcRepoURL "${{ env.YAML_REPO }}" \
            --arg srcTargetRevision "${{ github.event.repository.name }}-${{ github.event.number }}" \
            --arg labels "" \
            --arg deploymentId "${{ steps.create-github-deployment.outputs.deployment_id }}" \
            --arg appRepo "${{ github.repository }}" \
            --arg version "${{ github.event.number }}" \
            '{ appName: $appName, userGivenName: $userGivenName, destNamespace: $destNamespace, destServer: $destServer, srcPath: $srcPath, srcRepoURL: $srcRepoURL, srcTargetRevision: $srcTargetRevision, labels: $labels, deploymentId: $deploymentId, appRepo: $appRepo, version: $version }' > ${{ github.event.number }}/config.json

      - name: Push manifest to YAML Repo
        id: push-manifest
        uses: bonus83/copy_commit_push_tag@9b42a459878a8858c4dc38f2e40ccb4ba17fdde8
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITOPS_TOKEN }}
        with:
          source_file: "${{ github.event.number }}"
          destination_repo: "junipersquare/application-manifests"
          destination_folder: "${{ github.event.repository.name }}/preview"
          user_email: "junibot@junipersquare.com"
          user_name: "junibot@junipersquare.com"
          commit_message: "Deploying preview for ${{ github.event.number }}."
          commit_tag: "${{ github.event.repository.name }}-${{ steps.vars.outputs.deployment_hash }}-${{ github.event.number }}"

      - name: Create PR comment
        uses: junipersquare/actions-comment-pull-request@v1
        with:
          message: '
            Preview environment has been deployed. The site should be accessible momentarily.
            Quick Access: [fund-admin.pr${{ github.event.number }}.preview.junipersquare.us](https://fund-admin.pr${{ github.event.number }}.preview.junipersquare.us)
          '
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

